### ISSUE TITLE
Shutdown does not work

### ISSUE THREAD

**Issue by dominikzogg** [boxcutter/debian#16] opened 2015-08-14 05:00 UTC
https://github.com/dominikzogg/vagrant-php/issues/15

**Comment by annawake** [comment] 2015-09-28 02:27
Not clear on what the issue is, closing for now.

**Closed as completed by annawake** 2015-09-28 02:27 UTC

**Comment by dominikzogg** [comment] 2015-09-28 05:04
@annawake Seems to be solved, at the moments this PR gets merged: https://github.com/mitchellh/vagrant/pull/6315
